# Nombre de la aplicaci\u00f3n
spring.application.name=Variety

# BASE DE DATOS H2 (persistente en archivo)
# Ruta de la BD
spring.datasource.url=jdbc:h2:file:./data/varietydb
# Driver H2
spring.datasource.driverClassName=org.h2.Driver
# Usuario por defecto
spring.datasource.username=sa
# Sin contrase\u00f1a
spring.datasource.password=

# JPA / HIBERNATE
# Actualiza schema sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Muestra SQL en consola
spring.jpa.show-sql=true

# CONSOLA WEB H2
# Activar consola H2
spring.h2.console.enabled=true
# URL de acceso
spring.h2.console.path=/h2-console

# SERVIDOR
# Puerto del servidor
server.port=8080
# Duraci\u00f3n de sesi\u00f3n: 2 minutos
server.servlet.session.timeout=2m
# JWT (clave solo para desarrollo)
jwt.secret=EstaEsMiClaveSecretaSuperSeguraParaFirmarElJWTMinimalistaDeSpring123456

# LOGGING
# Nivel general
logging.level.root=INFO
# Debug para JWT
logging.level.com.example.Variety.jwt.JwtRequestFilter=DEBUG
# Debug para Security
logging.level.org.springframework.security=DEBUG
